extension: [".ts"]
include: ["lib/**/*.ts"]
exclude: ["/node_modules.nosync/**"]
reporter: ["text", "html"]
cache: true
sourceMap: true
instrument: true
compact: true
checkcoverage": true
branches: 80
lines: 90
functions: 80
statements: 90
temp-dir: ".nyc_output.nosync"
